### ISSUE TITLE
"View genomic context" links are incorrect

### ISSUE THREAD

**Issue by zreitz** [SJShaw/mibig-html#1]
“View genomic context” (on any record, any gene) uses the MIBiG accession rather than the original NCBI one.

Ex from [BGC0001021](https://mibig.secondarymetabolites.org/repository/BGC0001021/index.html#r1c1):
http://www.ncbi.nlm.nih.gov/projects/sviewer/?Db=gene&DbFrom=protein&Cmd=Link&noslider=1&id=BGC0001021.1&from=2652067&to=2677115

Should point to 
http://www.ncbi.nlm.nih.gov/projects/sviewer/?Db=gene&DbFrom=protein&Cmd=Link&noslider=1&id=AL123456.3&from=2652067&to=2677115

**Comment by SJShaw** [comment]
Fixed in 74ecb8f
